title: Lambda
description: I hope the field of computer science never loses its sense of fun.

menu:
  Home: /
  About: /about
  Github: https://github.com/zeqing-guo
  RSS: /atom.xml

rss: /atom.xml

# your name
signoff: Zeqing Guo

# disqus comment thread for post header options ( leave blank if unwanted )
disqus_shortname: JasonGuo92

# set tracking, UA-XXXX-Y
google_analytics: 
